name: "Swagger Modifier"
author: "Hayato Takahashi"
description: "AWS Api-Gatewayで取り込めるようにOpenAPI（Swagger）を編集する"
branding:
  icon: plus
  color: orange
inputs:
  input-file-path: # id of input
    description: "input swagger file path in your repository. ex: `sample/sampleTodo.yaml`"
    required: true
  output-file-path:
    description: "output swagger file path in your repository. ex: `sample/output.yaml`"
    required: true
  env:
    description: 'environment for creating swagger file\n this appears in lambda name.'
    required: false
    default: "dev"
  service-name:
    description: 'Service name for this swagger file. Default value is `info.tile` in swagger file. \nthis appears in lambda name.'
    required: false
  origin:
    description: "origin domain used in api.ex:`https://sample-api.com`"
    required: true
  cognito-user-pool-id:
    description: "cognito user pool id for authentication. PLEASE set this value from github secrets."
    required: true
  output-file-format:
    description: "file format for output swagger file. You can choose `json` or `yaml`"
    required: false
    default: "yaml"
  github_ref:
    description: "DO NOT SPECIFY THIS VALUE. use as variable inside script."
    required: false
    default: ${{ github.action_ref }}

runs:
  using: "composite"
  steps:
    - name: copy all files to executable path
      run: cp -a ./../../_actions/HayatoTakahashi129/swaggerModifier/${{ inputs.github_ref }}/. ./../../_actions/HayatoTakahashi129/swaggerModifier/
      shell: bash
    - name: "modify openapi swagger file"
      uses: ./../../_actions/HayatoTakahashi129/swaggerModifier/.github/actions/modify-swagger
      with:
        input-file-path: ${{ inputs.input-file-path }}
        output-file-path: ${{ inputs.output-file-path }}
        env: ${{ inputs.env }}
        service-name: ${{ inputs.service-name }}
        origin: ${{ inputs.origin }}
        cognito-user-pool-id: ${{ inputs.cognito-user-pool-id }}
        output-file-format: ${{ inputs.output-file-format }}
    - name: "commit modified swagger file to repository"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Modify Swagger by github action"
